// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://dealerone.processmyquote.com',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  aq3Url: 'https://aq3.processmyquote.com/DemoAgent',
  transactionFee: 0.98,
  dealerCode: 'ewaldkia',
  dealerLogo: 'ewald-logo.svg',
  sellingTitle: 'Sell',
  sellingUrl: 'https://maxallowance.com/trade1',
  sellingDesc: `
            <p>We've partnered with MaxAllowance.com to help you sell your vehicle online.<p>
            <p>They provide a comprehensive service to help you get the maximum
            price possible for your vehicle, whether you are trading it
            in for a new vehicle or just selling it outright.</p>`,
  tagline: `The Ewald Kia Car Loan Calculator lets you shop vehicles
  and a protection package that matches your ideal weekly budget.`,
};
